# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Michael Hentges Blog
email: mike@mhentges.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog for Michael Hentges, and Hentges.AI LLC
baseurl: "" # the subpath of your site, e.g. /blog
domain: mikehentges.github.io
url: "https://mikehentges.gihub.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/Chicago

social:
  name: Michael Hentges
  links:
    - https://github.com/mikehentges
    - https://twitter.com/HentgesMike

collections:
  pages:
    output: true
    permalink: /:title

permalink: /:slug

# - this works, now in index2.html in the /blog directory
#paginate: 5
#pagination_path: "blog/page:num/"

twitter_username: HentgesMike
github_username: mikehentges

highlighter: rogue
syntax_highligher: rogue

sass:
  sass_dir: _sass
  style: compressed

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-paginate
  - rogue
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-datapage-generator
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Makefile
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

page_gen:
  - data: categories
    template: category_page
    dir: /
    index_files: false
    name: category
    debug: true
